DROP TABLE IF EXISTS ANIMAL_TOYS;
DROP TABLE IF EXISTS MY_ANIMALS;
DROP TABLE IF EXISTS TOY;
DROP TABLE IF EXISTS STABLE;
DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE ADDRESS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    street VARCHAR(150),
    number INT,
    place VARCHAR(150)
);

CREATE TABLE STABLE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    max_animals INT,
    address_id BIGINT,
    FOREIGN KEY (address_id) REFERENCES ADDRESS(id)
);

CREATE TABLE MY_ANIMALS (
    name VARCHAR(100) PRIMARY KEY,
    age INT,
    stable_id BIGINT,
    FOREIGN KEY (stable_id) REFERENCES STABLE(id)
);

CREATE TABLE TOY (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);

CREATE TABLE ANIMAL_TOYS (
    animal_id VARCHAR(100),
    toy_id BIGINT,
    PRIMARY KEY (animal_id, toy_id),
    FOREIGN KEY (animal_id) REFERENCES MY_ANIMALS(name),
    FOREIGN KEY (toy_id) REFERENCES TOY(id)
);
