DROP TABLE IF EXISTS MY_ANIMALS;
DROP TABLE IF EXISTS STABLE;
DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE ADDRESS(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    street VARCHAR(150),
    number INT,
    place VARCHAR(150)
);

CREATE TABLE STABLE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    max_animals INT,
    address_id BIGINT,
    FOREIGN KEY (address_id) REFERENCES ADDRESS
);

CREATE TABLE MY_ANIMALS (
    name VARCHAR(100) PRIMARY KEY,
    age INT,
    stable_id BIGINT,
    FOREIGN KEY (stable_id) REFERENCES STABLE
);
