DROP TABLE IF EXISTS MY_ANIMALS;
DROP TABLE IF EXISTS STABLE;

CREATE TABLE STABLE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    max_animals INT
);

CREATE TABLE MY_ANIMALS (
    name VARCHAR(100) PRIMARY KEY,
    age INT,
    stable_id BIGINT,
    FOREIGN KEY (stable_id) REFERENCES STABLE
);
